"""company replica and inbox tables

Revision ID: 0be5b47cc066
Revises:
Create Date: 2026-08-27 10:55:39.091053

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import LtreeType

# revision identifiers, used by Alembic.
revision: str = "0be5b47cc066"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_replica",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inbox_event",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("consumer_name", sa.String(length=127), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", "consumer_name"),
    )
    op.create_table(
        "position",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_replica.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "name", name="unique_position_company"),
    )
    op.create_index(op.f("ix_position_company_id"), "position", ["company_id"], unique=False)
    op.create_table(
        "users_replica",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_replica.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_replica_company_id"), "users_replica", ["company_id"], unique=False)
    op.create_table(
        "struct_adm",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", LtreeType(), nullable=False),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_replica.id"],
        ),
        sa.ForeignKeyConstraint(["manager_id"], ["users_replica.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_struct_adm_company_id"), "struct_adm", ["company_id"], unique=False)
    op.create_index(op.f("ix_struct_adm_manager_id"), "struct_adm", ["manager_id"], unique=False)
    op.create_index(op.f("ix_struct_adm_path"), "struct_adm", ["path"], unique=False)
    op.create_table(
        "struct_adm_position",
        sa.Column("struct_adm_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["struct_adm_id"], ["struct_adm.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("struct_adm_id", "position_id"),
    )
    op.create_table(
        "users_position",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("struct_adm_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Enum("member", "manager", name="role", native_enum=False), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["struct_adm_id"], ["struct_adm.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users_replica.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "position_id", "struct_adm_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_position")
    op.drop_table("struct_adm_position")
    op.drop_index(op.f("ix_struct_adm_path"), table_name="struct_adm")
    op.drop_index(op.f("ix_struct_adm_manager_id"), table_name="struct_adm")
    op.drop_index(op.f("ix_struct_adm_company_id"), table_name="struct_adm")
    op.drop_table("struct_adm")
    op.drop_index(op.f("ix_users_replica_company_id"), table_name="users_replica")
    op.drop_table("users_replica")
    op.drop_index(op.f("ix_position_company_id"), table_name="position")
    op.drop_table("position")
    op.drop_table("inbox_event")
    op.drop_table("company_replica")
    # ### end Alembic commands ###
