"""path is unique in table StructAdm

Revision ID: 2875db94bb1c
Revises: 0be5b47cc066
Create Date: 2026-08-27 15:34:47.421005

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2875db94bb1c"
down_revision: str | Sequence[str] | None = "0be5b47cc066"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_struct_adm_path"), table_name="struct_adm")
    op.create_unique_constraint(None, "struct_adm", ["path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "struct_adm", type_="unique")
    op.create_index(op.f("ix_struct_adm_path"), "struct_adm", ["path"], unique=False)
    # ### end Alembic commands ###
