"""add outbox_event tables

Revision ID: 4af26c574ece
Revises: 71e54d787eeb
Create Date: 2026-09-05 10:15:21.407466

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4af26c574ece"
down_revision: str | Sequence[str] | None = "71e54d787eeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
