"""remove manager_id from struct_adm

Revision ID: 71e54d787eeb
Revises: f965436f8fb1
Create Date: 2026-09-03 16:14:01.456581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71e54d787eeb"
down_revision: str | Sequence[str] | None = "f965436f8fb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_struct_adm_manager_id"), table_name="struct_adm")
    op.drop_constraint(op.f("struct_adm_manager_id_fkey"), "struct_adm", type_="foreignkey")
    op.drop_column("struct_adm", "manager_id")
    op.create_index(
        "uq_users_position_one_manager_struct",
        "users_position",
        ["struct_adm_id"],
        unique=True,
        postgresql_where=sa.text("role = 'manager'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_position_one_manager_struct",
        table_name="users_position",
        postgresql_where=sa.text("role = 'manager'"),
    )
    op.add_column("struct_adm", sa.Column("manager_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("struct_adm_manager_id_fkey"), "struct_adm", "users_replica", ["manager_id"], ["id"], ondelete="SET NULL"
    )
    op.create_index(op.f("ix_struct_adm_manager_id"), "struct_adm", ["manager_id"], unique=False)
    # ### end Alembic commands ###
