"""add FK for struct_adm_id and position_id in users_position tables

Revision ID: f965436f8fb1
Revises: 2875db94bb1c
Create Date: 2026-09-03 14:22:27.533059

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f965436f8fb1"
down_revision: str | Sequence[str] | None = "2875db94bb1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_position_struct_adm_id_fkey"), "users_position", type_="foreignkey")
    op.drop_constraint(op.f("users_position_position_id_fkey"), "users_position", type_="foreignkey")
    op.create_foreign_key(
        None,
        "users_position",
        "struct_adm_position",
        ["struct_adm_id", "position_id"],
        ["struct_adm_id", "position_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(None, "users_position", "position", ["position_id"], ["id"])
    op.create_foreign_key(None, "users_position", "struct_adm", ["struct_adm_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_position", type_="foreignkey")
    op.drop_constraint(None, "users_position", type_="foreignkey")
    op.drop_constraint(None, "users_position", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_position_position_id_fkey"),
        "users_position",
        "position",
        ["position_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("users_position_struct_adm_id_fkey"),
        "users_position",
        "struct_adm",
        ["struct_adm_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
