networks:
  microservices:
    driver: bridge

volumes:
  auth_postgres_data:
  kafka-data:

services:
  auth_postgres:
    image: postgres:17-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      retries: 5
    networks:
      - microservices

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    volumes:
      - ./auth_service:/app/auth_service
    environment:
      APP_SECRET_KEY: ${AUTH_APP_SECRET_KEY}
      DB_USER: ${AUTH_DB_USER}
      DB_PASSWORD: ${AUTH_DB_PASSWORD}
      DB_HOST: ${AUTH_DB_HOST}
      DB_PORT: "5432"
      DB_NAME: ${AUTH_DB_NAME}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "${AUTH_SERVICE_PORT}:8000"
    depends_on:
      auth_postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - microservices

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "${KAFKA_BIND_HOST}:9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:29092 --list"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - microservices