"""revoked cascad saga_id from user and account tables

Revision ID: 402e361a9cbd
Revises: 6f5a0ce29741
Create Date: 2026-09-13 12:07:25.735143

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "402e361a9cbd"
down_revision: str | Sequence[str] | None = "6f5a0ce29741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("registration_saga_invite_id_fkey"), "registration_saga", type_="foreignkey")
    op.drop_constraint(op.f("registration_saga_user_id_fkey"), "registration_saga", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("registration_saga_user_id_fkey"), "registration_saga", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("registration_saga_invite_id_fkey"),
        "registration_saga",
        "invite",
        ["invite_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
