"""added deadline_at and last_error in registration_saga

Revision ID: 5403fde879af
Revises: 967980c2666d
Create Date: 2026-10-10 16:23:11.235495

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5403fde879af"
down_revision: str | Sequence[str] | None = "967980c2666d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("registration_saga", sa.Column("last_error", sa.String(), nullable=True))
    op.add_column("registration_saga", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration_saga", "deadline_at")
    op.drop_column("registration_saga", "last_error")
    # ### end Alembic commands ###
