"""added registration_saga and smal change in invite

Revision ID: 67a502ab21c4
Revises: a85a26a1fe03
Create Date: 2026-09-10 16:17:37.693863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67a502ab21c4"
down_revision: str | Sequence[str] | None = "a85a26a1fe03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_saga",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("invite_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "org_completed",
                "tasks_completed",
                "completed",
                "compensating",
                "failed",
                name="onboardingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invite_id"], ["invite.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_registration_saga_company_id"), "registration_saga", ["company_id"], unique=False)
    op.create_index(op.f("ix_registration_saga_correlation_id"), "registration_saga", ["correlation_id"], unique=True)
    op.create_index(op.f("ix_registration_saga_invite_id"), "registration_saga", ["invite_id"], unique=True)
    op.create_index(op.f("ix_registration_saga_user_id"), "registration_saga", ["user_id"], unique=False)
    op.add_column("invite", sa.Column("struct_adm_id", sa.UUID(), nullable=True))
    op.add_column("invite", sa.Column("position_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite", "position_id")
    op.drop_column("invite", "struct_adm_id")
    op.drop_index(op.f("ix_registration_saga_user_id"), table_name="registration_saga")
    op.drop_index(op.f("ix_registration_saga_invite_id"), table_name="registration_saga")
    op.drop_index(op.f("ix_registration_saga_correlation_id"), table_name="registration_saga")
    op.drop_index(op.f("ix_registration_saga_company_id"), table_name="registration_saga")
    op.drop_table("registration_saga")
    # ### end Alembic commands ###
