"""added inbox_event table in auth_service

Revision ID: 6f5a0ce29741
Revises: 67a502ab21c4
Create Date: 2026-09-10 16:57:59.764750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5a0ce29741"
down_revision: str | Sequence[str] | None = "67a502ab21c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_event",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("consumer_name", sa.String(length=127), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", "consumer_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inbox_event")
    # ### end Alembic commands ###
