"""add user_id to invite

Revision ID: 9598f19c1326
Revises: b2b0b94eae16
Create Date: 2026-08-20 15:37:22.905099

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9598f19c1326"
down_revision: str | Sequence[str] | None = "b2b0b94eae16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_invite_user_id"), "invite", ["user_id"], unique=False)
    op.create_foreign_key(None, "invite", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint(None, "members", ["invite_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "members", type_="unique")
    op.drop_constraint(None, "invite", type_="foreignkey")
    op.drop_index(op.f("ix_invite_user_id"), table_name="invite")
    op.drop_column("invite", "user_id")
    # ### end Alembic commands ###
