"""added failed_message

Revision ID: 967980c2666d
Revises: b73fd15a67bc
Create Date: 2026-10-05 11:02:05.977532

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "967980c2666d"
down_revision: str | Sequence[str] | None = "b73fd15a67bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("consumer_name", sa.String(length=127), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("partition", sa.Integer(), nullable=False),
        sa.Column("offset", sa.BigInteger(), nullable=False),
        sa.Column("raw_value", postgresql.BYTEA(), nullable=True),
        sa.Column("raw_key", postgresql.BYTEA(), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "resolved", "discarded", name="failedmessagestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consumer_name", "topic", "partition", "offset", name="unique_failed_kafka_message"),
    )
    op.create_index(op.f("ix_failed_message_correlation_id"), "failed_message", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_failed_message_event_id"), "failed_message", ["event_id"], unique=False)
    op.create_index(op.f("ix_failed_message_status"), "failed_message", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_failed_message_status"), table_name="failed_message")
    op.drop_index(op.f("ix_failed_message_event_id"), table_name="failed_message")
    op.drop_index(op.f("ix_failed_message_correlation_id"), table_name="failed_message")
    op.drop_table("failed_message")
    # ### end Alembic commands ###
