"""change invite tables: added attempts, deleted company_id and role

Revision ID: b2b0b94eae16
Revises: c47b69cc56bf
Create Date: 2026-08-06 09:34:15.355714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2b0b94eae16"
down_revision: str | Sequence[str] | None = "c47b69cc56bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite", sa.Column("attempts", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("invite_company_id_fkey"), "invite", type_="foreignkey")
    op.drop_column("invite", "role")
    op.drop_column("invite", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite", sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column("invite", sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("invite_company_id_fkey"), "invite", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("invite", "attempts")
    # ### end Alembic commands ###
