"""add account_id to invite

Revision ID: d238637cfc64
Revises: 9598f19c1326
Create Date: 2026-08-21 15:26:29.863455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd238637cfc64'
down_revision: Union[str, Sequence[str], None] = '9598f19c1326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invite_account_id'), 'invite', ['account_id'], unique=False)
    op.create_foreign_key(None, 'invite', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.drop_index(op.f('ix_invite_account_id'), table_name='invite')
    op.drop_column('invite', 'account_id')
    # ### end Alembic commands ###
