"""added enum in status from task table

Revision ID: 5c503ece2616
Revises: 27ba380b3a39
Create Date: 2026-09-09 08:31:19.422289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c503ece2616"
down_revision: str | Sequence[str] | None = "27ba380b3a39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("todo", "in_progress", "in_review", "done", "cancelled", name="taskstatus", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "status",
        existing_type=sa.Enum(
            "todo", "in_progress", "in_review", "done", "cancelled", name="taskstatus", native_enum=False
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
